[package]
name = "antibox-wayland"
version = "1.2.0"
edition = "2021"

[dependencies]
antibox-core = { path = "../core" }

[features]
default = []
smithay = ["dep:smithay"]

[dependencies.smithay]
version = "0.7"
optional = true
default-features = false
features = [
    "backend_winit",
    "backend_egl",
    "renderer_gl",
    "wayland_frontend",
    "desktop",
    "use_system_lib",
    "xwayland",
]
