[package]
name = "antibox"
version = "1.3.0"
edition = "2021"

[lib]
name = "antibox"
path = "src/lib.rs"

[[bin]]
name = "antibox"
path = "src/main.rs"

[dependencies]
antibox-core = { path = "../core" }
antibox-ui = { path = "../ui" }
antibox-x11 = { path = "../x11" }
antibox-wayland = { path = "../wayland" }
antibox-wm = { path = "../wm" }

[[bin]]
name = "antibox-settings"
path = "src/bin/antibox-settings.rs"

[features]
default = []
wayland = ["antibox-wayland/smithay"]

[[bin]]
name = "antibox-wayland"
path = "src/bin/antibox-wayland.rs"
required-features = ["wayland"]
