[package]
name = "antibox"
version = "1.1.0"
edition = "2021"

[lib]
name = "antibox"
path = "src/lib.rs"

[[bin]]
name = "antibox"
path = "src/main.rs"

[dependencies]
antibox-core = { path = "../core" }
antibox-ui = { path = "../ui" }
antibox-x11 = { path = "../x11" }
antibox-wm = { path = "../wm" }
